### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by lividhen** [safijari/Reshadeck#1]
Enabling a reshade effect seems to just turn off the display. It can be fixed by force shutting off the device or blind selecting no shader. 

https://github.com/safijari/Reshadeck/assets/42221797/8aaddba8-701e-4e03-9c98-5eac3b63f5f1

### Log
-----
[2023-12-18 20.40.38.log](https://github.com/safijari/Reshadeck/files/13710942/2023-12-18.20.40.38.log)

**Comment by lividhen** [comment]
Hm, attempted to apply the fix in this stack exchange post and it suddenly started working.

https://stackoverflow.com/questions/70687625/attributeerror-rootlogger-object-has-no-attribute-basicconfig

**Comment by jnpitnrplann** [comment]
Same issue here, however the black screen will not disappear? I shut it down and everything and its still black. bruh...

**Comment by KrisCris** [comment]
I had the same issue, which constantly happened when recording using Decky Recorder.

**Comment by safijari** [comment]
This is no longer an issue.
