### ISSUE TITLE
Not loading on Stable OS after May 7th 2024 update

### ISSUE THREAD

**Issue by midnightcatwalk** [safijari/Reshadeck#12]
Reshadeck throws an error upon launching the Deck after the latest Stable update, and opening the plugin also fails, showing an error beginning with the following:

`TypeError: Cannot read properties of undefined (reading ‘Title’) at eval (eval at importReactPlugin)…at PluginLoader.importReactPlugin…at async PluginLoader.importPlugin`

**Comment by Slvrtnge** [comment]
Second this! Same issue a lot of plugins are experiencing and has been fixed so far by Game Theme Music and Animation changer if it helps to see how they fixed the issue!

**Comment by ricardblasco** [comment]
Yes, I hope this can be fixed, this plugin is a must

**Comment by bryc** [comment]
Confirmed broken here as well.

This needs to be reverted ASAP.

This is a breaking change that has arrived as part of an automatic update system.

Things like this happening is why people disable automatic updates and seek ways to downgrade. Speaking of - is there a way to undo this update?

**Comment by ricardblasco** [comment]
Fixed with the version 2.0.0 of the plugin. Huge thank you to @safijari 👏
