### ISSUE TITLE
steam crashing when enabling custom shader

### ISSUE THREAD

**Issue by creeperita09** [safijari/Reshadeck#3]
so i was trying to make a shader to flip the screen image horizontally (so i can watch videos on my SD from the reflection on a train window, don't ask why lol) and found thisxon the reshade forum:

```
#include "ReShade.fxh"

float4 FlipPass(float4 vpos : SV_Position, float2 texcoord : TexCoord) : SV_Target
{
texcoord.x = 1-texcoord.x;//horizontal flip
texcoord.y = 1-texcoord.y;//vertical flip
float4 color = tex2D(ReShade::BackBuffer, texcoord);
return color;
}

technique Flip
{
pass
{
VertexShader = PostProcessVS;
PixelShader = FlipPass;
}
}
```
But enabling that shader (wich i named mirror.fx) crashes steam (not steam os, just steam) and i can't figure why.
Anyone got any clues?

**Comment by creeperita09** [comment]
oh just read
> Some shaders can cause the Deck to crash

well anyway why is it crashing with that shader?

**Comment by safijari** [comment]
> oh just read
> 
> > Some shaders can cause the Deck to crash
> 
> well anyway why is it crashing with that shader?

I don't know. This plugin is just a wrapper over gamescope. You can open an issue on gamescope about this and ask them why the crash happens
