### ISSUE TITLE
Certain shaders not working (FXAA, TAA, FakeHDR)

### ISSUE THREAD

**Issue by BrochachoTheBro** [safijari/Reshadeck#8]
This is an excellent plugin, but I've noticed some shaders don't seem to be rendering at all. The 3 shaders packed in (Samsung fringing fix, Mattias CRT, VHS) as well as CRT Royale work just fine, but FXAA, TAA, and FakeHDR seem to have no effect. Any dependencies I'm missing? Is this something that'd need to be fixed at plugin-level?

**Comment by safijari** [comment]
A number of plugins (especially AA plugins) need data that isn't available to Gamescope and therefore cannot work. There isn't anything I can do about that unfortunately
